export const ACTIONS = {
  SET_USER: "SET_USER",
  SET_PROSPECTS: "SET_PROSPECTS",
  SET_PROSPECT_LIST: "SET_PROSPECT_LIST",
  SET_SINGUP_STEP: "SET_SINGUP_STEP",

  START_UPLOADE_WORKER: "START_UPLOADE_WORKER",
  UPDATE_UPLOADE_WORKER: "UPDATE_UPLOADE_WORKER",
  COMPLETED_UPLOADE_WORKER: "COMPLETED_UPLOADE_WORKER",
  ERROR_UPLOADE_WORKER: "ERROR_UPLOADE_WORKER",
  IDLE_UPLOADE_WORKER: "IDLE_UPLOADE_WORKER",
};

export const UPLOAD_STATUS = {
  STARTED: "started",
  UPLOADED_ONE: "uploaded one item",
  COMPLETED_UPLOAD: "completed to upload",
  ERROR: "error occured",
};
