/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5d525e61-ddec-42b0-8898-8ab088d4e7e6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_MmFPWqRd0",
    "aws_user_pools_web_client_id": "3cebi25uljobok20b3vfn2ej4s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nrwqcmhbgvdaxaloszxp72xjvu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gsbg2tb745bi5kwruzwtbyoaj4"
};


export default awsmobile;
